# Dockerfile.prod

FROM tiangolo/uvicorn-gunicorn:python3.11-slim

RUN apt-get update && apt-get install -y netcat

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN pip install -e app/

RUN pip install transformers

RUN pip install fastapi

RUN pip install 'uvicorn[standard]'

RUN pip install librosa

RUN pip install ipywidgets

RUN pip install python-multipart

COPY . .